apiVersion: v1
kind: Template
labels:
  app: project-service
metadata:
  annotations:
    description: Freelancer4j project service persistent template for MongoDB
  name: freelancer4j-project-mongodb
objects:
# Catalog Service
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: project-service
    name: project-mongodb
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      deploymentconfig: project-mongodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: project-service
    name: project-mongodb
  spec:
    replicas: 1
    selector:
      deploymentconfig: project-mongodb
    strategy:
      recreateParams:
        post:
          execNewPod:
            command:
              - /bin/sh
              - -i
              - -c
              - sleep 10 && /opt/rh/rh-mongodb32/root/usr/bin/mongo $PROJECT_MONGODB_SERVICE_HOST:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="$MONGODB_INIT"
            containerName: project-mongodb
            env:
            - name: MONGODB_INIT
              value: 
                db.projects.createIndex({ "projectId":1 });
                db.projects.createIndex({ "projectStatus":1 });
                db.projects.insert({"_id":"329291","projectId":"329291","ownerFirstName":"Mai", "ownerLastName":"Oyama", "ownerEmail":"mai.oyama@exmaple.com", "projectTitle":"project-1","projectDescription":"project-1-desc", "projectStatus":"open"});
                db.projects.insert({"_id":"329292","projectId":"329292","ownerFirstName":"Seiko", "ownerLastName":"Kotani", "ownerEmail":"seiko.kotani@exmaple.com", "projectTitle":"project-2","projectDescription":"project-2-desc", "projectStatus":"open"});
                db.projects.insert({"_id":"329293","projectId":"329293","ownerFirstName":"Niki", "ownerLastName":"Imai", "ownerEmail":"niki.imai@exmaple.com", "projectTitle":"project-3","projectDescription":"project-3-desc", "projectStatus":"completed"});
                db.projects.insert({"_id":"329294","projectId":"329294","ownerFirstName":"Niki", "ownerLastName":"Imai", "ownerEmail":"niki.imai@exmaple.com", "projectTitle":"project-4","projectDescription":"project-4-desc", "projectStatus":"in_progres"});
                db.projects.insert({"_id":"329295","projectId":"329295","ownerFirstName":"Mai", "ownerLastName":"Oyama", "ownerEmail":"mai.oyama@exmaple.com", "projectTitle":"project-5","projectDescription":"project-5-desc", "projectStatus":"cancelled"});
                db.projects.insert({"_id":"329296","projectId":"329296","ownerFirstName":"Niki", "ownerLastName":"Imai", "ownerEmail":"niki.imai@exmaple.com", "projectTitle":"project-6","projectDescription":"project-6-desc", "projectStatus":"in_progress"});
                db.projects.insert({"_id":"329297","projectId":"329297","ownerFirstName":"Seiko", "ownerLastName":"Kotani", "ownerEmail":"seiko.kotani@exmaple.com", "projectTitle":"project-7","projectDescription":"project-7-desc", "projectStatus":"completed"});
          failurePolicy: ignore
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: project-service
          deploymentconfig: project-mongodb
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MONGODB_USER
            value: ${PROJECT_DB_USERNAME}
          - name: MONGODB_PASSWORD
            value: ${PROJECT_DB_PASSWORD}
          - name: MONGODB_DATABASE
            value: ${PROJECT_DATABASE}
          - name: MONGODB_ADMIN_PASSWORD
            value: ${PROJECT_DB_PASSWORD}
          image: mongodb
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: project-mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: project-mongodb-data-pv
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - project-mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      application: project-mongodb
    name: project-mongodb-data-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
- description: Catalog Service database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: PROJECT_DB_USERNAME
  required: true
- description: Catalog Service database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: PROJECT_DB_PASSWORD
  required: true
- description: Catalog Service database name
  name: PROJECT_DATABASE
  required: true
  value: projectdb
